export const dictCountries = {
    "FRA": "France",
    "LVA": "Lettonie",
    "FIN": "Finlande",
    "ITA": "Italie",
    "DEU": "Allemagne",
    "BEL": "Belgique",
    "ESP": "Espagne",
    "IRL": "Irlande",
    "CZE": "Rép. tchèque",
    "ISL": "Islande",
    "DNK": "Danemark",
    "LUX": "Luxembourg",
    "SWE": "Suède",
    "PRT": "Portugal",
    "GRC": "Grèce",
    "AUT": "Autriche",
    "LTU": "Lituanie",
    "MNE": "Monténégro",
}